[build]
  # Base directory: Where to change directory before starting the build.
  # Should be the root of the frontend package.
  base = "packages/frontend/editor-ui"

  # Publish directory: Directory (relative to the 'base' directory) that contains the deploy-ready assets.
  # Vite's default output is 'dist', created inside the 'base' directory.
  publish = "dist"

  # Build command: Command to run to build your site.
  # Install dependencies from the root first, then run the build script.
  # Removed VUE_APP_PUBLIC_PATH as Vite should handle base path automatically for root deployment.
  # NODE_OPTIONS might still be needed for memory.
  command = "pnpm install --frozen-lockfile && cross-env NODE_OPTIONS=\" --max-old-space-size=8192\" pnpm build" 
