[build]
  # Base directory: Where to change directory before starting the build.
  # Should be the root of the frontend package.
  base = "packages/frontend/editor-ui"

  # Publish directory: Directory (relative to the 'base' directory) that contains the deploy-ready assets.
  # Vite's default output is 'dist', created inside the 'base' directory.
  publish = "dist"

  # Build command: Command to run to build your site.
  # We need to install dependencies first using pnpm (assuming it's installed globally or via Netlify build image) 
  # then run the build script from the package.json.
  # Note: The VUE_APP_PUBLIC_PATH might need adjustment depending on how the backend is hosted.
  # Note: We install dependencies from the root to handle the pnpm workspace.
  command = "pnpm install --frozen-lockfile && pnpm build" 
